### ISSUE TITLE
Chapter 12 - I/O Project

### ISSUE THREAD

**Issue by ericdouglas** [rust-br/rust-book-pt-br#14]

**Comment by leoyvens** [comment]
O @amargarido vai trabalhar nesse.

**Comment by amargarido** [comment]
Já comecei. :)

Em 17 de fev de 2018 10:00 AM, "Leonardo Yvens" <notifications@github.com>
escreveu:

O @amargarido <https://github.com/amargarido> vai trabalhar nesse.

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/rust-br/rust-book-pt-br/issues/14#issuecomment-366436700>,
or mute the thread

**Comment by amargarido** [comment]
Chuto 40% traduzido...

**Comment by amargarido** [comment]
Chuto 50% traduzido ...

**Comment by amargarido** [comment]
Chuto 70% traduzido ...

**Comment by amargarido** [comment]
Chuto 90% traduzido ...

**Comment by amargarido** [comment]
@leoyvens , achei minha tradução do Cap 12. Eu já tinha retirado os textos em inglês originai. Pergunta: quer ver os textos originai ou envio a tradução já em português?

**Comment by leoyvens** [comment]
@amargarido pode mandar com tudo em portugues.

**Comment by amargarido** [comment]
@leoyvens , acredito que já possa encerrar essa aqui.
